### ISSUE TITLE
Pink backgrounds on sprites in Safari

### ISSUE THREAD

**Issue by brandonreid** [PrefectHQ/graphs#108]
In the safari browser, sprites are rendering with a pink background rather than a transparent one for some reason.

**Comment by taylor-curran** [comment]
I have seen pink backgrounds in chrome as well. I tried in opera, and did not see the pink background.

**Comment by taylor-curran** [comment]
Also Nicholas says firefox does not show pink background.

**Comment by pleek91** [comment]
@brandonreid do you know how to reproduce this? Curious if v2 has this same issue or if this can be closed

**Comment by brandonreid** [comment]
I haven't seen this come up in a good while. Just checked in Safari again and not seeing it. Going to close this for now and we can open a new ticket if it does pop back up.
