### ISSUE TITLE
Display pending tasks

### ISSUE THREAD

**Issue by brandonreid** [PrefectHQ/graphs#109]
Currently the graph only shows items that have a start date.

Design and implement a way to show upcoming tasks and animate them onto the timeline of events when they begin.

Related to PrefectHQ/prefect#8968

**Comment by pleek91** [comment]
We won't be able to account for this without some major api changes since pending tasks can also be sub flow runs. Also the issue in question has been closed as stale. So closing this issue. Possibly will revisit in the future if this comes up again.
