### ISSUE TITLE
Recalculate the timescale at certain intervals when isRunning is true

### ISSUE THREAD

**Issue by brandonreid** [PrefectHQ/graphs#113]
When a flow run is running, it uses the initial time scale throughout the life of the run, until the browser is refreshed. This timescale should be more consistent and reactive as the timeline size grows.

A key goal with the graph is consistency in how it renders. So ideally, any time I hit refresh on a live flow run, I should see the same layout.

**Comment by pleek91** [comment]
This is better in v2 though still has the side effect that if a run is long enough to change the default scale multiplier when you refresh you'll get a different initial render. However you can manually adjust the multiplier even while running. I don't think this can be improved much and we're likely to not revisit so closing this issue.
