### ISSUE TITLE
Refactor bitmapFonts.ts

### ISSUE THREAD

**Issue by brandonreid** [PrefectHQ/graphs#63]
The `bitmapFonts.ts` service currently exists as a sort of singleton that doesn't quite fit with the advent of theme props. This needs to be rethought.

One idea was a service that can generate fonts on the fly for wherever one is needed, and retrieve duplicates from a cache. Wherever it's used will be responsible for re-asking for new fonts if styles changed.

**Comment by pleek91** [comment]
Doesn't exist in v2 so closing
