### ISSUE TITLE
Use spacing values from prefect-design

### ISSUE THREAD

**Issue by brandonreid** [PrefectHQ/graphs#68]
There is a series of spacing value overrides available from the Flow Run Timeline that can be populated with spacing values from orion-design. In order to do this, we need a way in orion-design to get the spacing values from tailwind.

Color values are populated in the UI as CSS variables, so they were easy enough to retrieve for the graph.

**Comment by pleek91** [comment]
I don't think this is an issue in v2 where the styles are much simpler.
